/*
 * Grupo 20
 * André Montenegro, Nº63755
 * Francisco Costa, Nº63691
 * Nicholas Antunes, Nº63783
 */
#ifndef MAIN_H_GUARD
#define MAIN_H_GUARD

#include "memory.h"

/* NOTE:
 * Header files can be replaced during evaluation.
 * Keep function signatures and structure fields consistent.
 */

/* Structure that stores the configuration and shared runtime data
 * used by the main process of SOestimate.
 *
 * Notice: although several fields below represent single integers or
 * integer arrays, they are declared as pointers because they refer to
 * shared-memory regions accessed by multiple processes. For example,
 * total_measurements conceptually stores just one int, but it must be
 * declared as int * so all processes access the same shared-memory
 * location. If it were declared as int, each process would keep its own
 * copy after fork(), and changes made by one process would not be
 * visible to the others.
 */
struct info_container
{
    int n_sensors;    // number of sensor processes
    int n_servers;    // number of server processes
    int buffers_size; // shared buffer size

    int *sensors_pids;     // process IDs of sensor processes
    int *controllers_pids; // process IDs of controller processes
    int *servers_pids;     // process IDs of server processes

    int *num_generated_measurements; // number of measurements generated by each sensor
    int *num_invalid_measurements;   // number of invalid measurements per sensor
    int *num_estimates;              // number of estimates produced by each server

    int *total_measurements; // total number of generated measurements in the system
    int *terminate;          // termination flag (1 means the system must stop)
};

/*
 * Function that reads and validates command-line arguments.
 * argc and argv contain the application parameters from the command line.
 * The validated values are stored in info.
 */
void main_args(int argc, char *argv[], struct info_container *info);

/*
 * Function that allocates dynamic memory needed by the application.
 * info provides sizes and receives PID arrays.
 * buffs receives dynamically allocated buffer container structures.
 */
void create_dynamic_memory_structs(struct info_container *info, struct buffers *buffs);

/*
 * Function that creates and initializes all shared-memory structures.
 * info contains sizes and shared counters/flags.
 * buffs receives shared-memory pointers for all communication buffers.
 */
void create_shared_memory_structs(struct info_container *info, struct buffers *buffs);

/*
 * Function that frees previously allocated dynamic memory.
 * info and buffs contain the pointers that must be released.
 */
void destroy_dynamic_memory_structs(struct info_container *info, struct buffers *buffs);

/*
 * Function that destroys all shared-memory regions used by the system.
 * info and buffs provide the shared-memory pointers and sizes needed.
 */
void destroy_shared_memory_structs(struct info_container *info, struct buffers *buffs);

/*
 * Function that creates all child processes (sensors, controllers, and servers).
 * The created process IDs are stored in info.
 * Shared buffers in buffs are passed to child process routines.
 */
void create_processes(struct info_container *info, struct buffers *buffs);

/*
 * Function responsible for user interaction.
 * It reads commands from stdin and triggers system operations.
 * info and buffs are used to access state, counters, and shared buffers.
 */
void user_interaction(struct info_container *info, struct buffers *buffs);

/*
 * Function that prints final SOestimate statistics before shutdown.
 * Data is read from counters stored in info.
 */
void write_final_statistics(struct info_container *info);

/*
 * Function that ends execution in an orderly way.
 * It sets terminate in info, waits for child processes, and prints final statistics.
 * buffs is used during the shutdown sequence.
 */
void end_execution(struct info_container *info, struct buffers *buffs);

/*
 * Function that waits for all previously created child processes to finish.
 * Process IDs are read from info.
 */
void wait_processes(struct info_container *info);

/*
 * Reads the estimate requested by the user for measurement cycle m_id.
 * When m_id is invalid or missing, the estimate is treated as unknown.
 */
void read_estimate(struct info_container *info, int m_id);

/*
 * Function that prints the current system status.
 * It shows configuration values, process IDs, and runtime counters from info.
 */
void print_stat(struct info_container *info);

/*
 * Function that prints detailed help for available commands.
 */
void help(void);

/*
 * Main function of SOestimate.
 * It initializes runtime structures, creates child processes,
 * runs user interaction, and then releases allocated resources.
 * argc and argv are the standard command-line parameters.
 */
int main(int argc, char *argv[]);

#endif
