/*
 * Grupo 20
 * André Montenegro, Nº63755
 * Francisco Costa, Nº63691
 * Nicholas Antunes, Nº63783
 */
#ifndef MEMORY_H_GUARD
#define MEMORY_H_GUARD

/* WARNING: DO NOT MODIFY THIS FILE
 * Header files may be replaced by the teachers during evaluation.
 * If function signatures or required definitions change, the project may fail to compile.
 */

typedef enum State
{
    REQUEST = 0,  // when the main/user request a measurement cycle
    MEASURED = 1, // when the sensor measures, changes the state to measured
    VALID = 2,    // after the controller validates, changes the state to valid or invalid
    INVALID = 3
} State;

typedef struct MeasurementInfo
{
    State state;         // state of the measurement
    int m_id;            // measurement sequence number, starting from 1
    int sensor_id;       // sensor id
    int controller_id;   // controller id
    double value;        // measured value generated by a sensor
    int counter_sensors; // when Main creates an instance of this struct, it initializes this field with the total number of sensors in the system; this counter indicates how many sensors still need to read this instance from the circular buffer and is decremented by each sensor that reads it
    int counter_servers; // number of servers that still need to read this measurement produced by a controller; initialized with the total number of servers and decremented each time a server reads it
} MeasurementInfo;

// Shared-memory identifiers used by SOestimate
#define ID_SHM_MAIN_SENSORS_PTR "SHM_MAIN_SENSORS_PTR"
#define ID_SHM_MAIN_SENSORS_BUFFER "SHM_MAIN_SENSORS_BUFFER"
#define ID_SHM_SENSORS_CONTROLLERS_PTR "SHM_SENSORS_CONTROLLERS_PTR"
#define ID_SHM_SENSORS_CONTROLLERS_BUFFER "SHM_SENSORS_CONTROLLERS_BUFFER"
#define ID_SHM_CONTROLLERS_SERVERS_LATEST "SHM_CONTROLLERS_SERVERS_LATEST"
#define ID_SHM_CONTROLLERS_SERVERS_VERSION "SHM_CONTROLLERS_SERVERS_VERSION"
#define ID_SHM_SENSORS_GENERATED "SHM_SENSORS_GENERATED"
#define ID_SHM_SENSORS_INVALID "SHM_SENSORS_INVALID"
#define ID_SHM_SERVERS_PROCESSED "SHM_SERVERS_PROCESSED"
#define ID_SHM_TOTAL_MEASUREMENTS "SHM_TOTAL_MEASUREMENTS"
#define ID_SHM_TERMINATE "SHM_TERMINATE"

// Auxiliary pointers for circular buffers
// Notice: a circular buffer has a single shared in/out pair for the
// whole buffer, not one in/out pair per sensor. In the main->sensors
// buffer, all sensors read from the same shared buffer, and each slot
// remains valid until every sensor reads it.
struct pointers
{
    int in;  // next write position
    int out; // next read position
};

// Circular buffer descriptor for measurement storage
struct circ_buffer
{
    struct pointers *ptrs;   // in/out shared pointers
    MeasurementInfo *buffer; // array storage area
};

// Random-access buffer descriptor
struct ra_buffer
{
    int *ptrs;               
    MeasurementInfo *buffer; // array storage area
};

// Groups all shared buffers used by process communication
struct buffers
{
    struct circ_buffer *buff_main_sensors;      // main -> sensors requests
    struct ra_buffer *buff_sensors_controllers; // sensors -> controllers measurements
    struct ra_buffer *buff_controllers_servers; // controllers -> servers measurements
};

/* Allocates dynamic memory with size bytes, initializes it with zeros,
 * and returns a pointer to the allocated area.
 */
void *allocate_dynamic_memory(int size);

/* Function that reserves a shared-memory region with the size indicated
 * by size and the name name, fills that memory region with the value 0,
 * and returns a pointer to it. The result of getuid() can be concatenated
 * to name to make the shared-memory name unique for the current user.
 */
void *create_shared_memory(char *name, int size);

/* Frees a previously allocated dynamic-memory region.
 */
void deallocate_dynamic_memory(void *ptr);

/* Unmaps and removes a previously created shared-memory region.
 */
void destroy_shared_memory(char *name, void *ptr, int size);

/* Writes one MeasurementInfo request in the main->sensors circular buffer.
 * Returns 1 on success, or 0 if no free slot is available.
 */
int write_main_sensors_buffer(struct circ_buffer *buffer, int buffer_size, const MeasurementInfo *req);

/* Reads the next pending MeasurementInfo for expected_m_id from the main->sensors buffer.
 * If no request exists yet, sets req->m_id to -1.
 */
void read_main_sensors_buffer(struct circ_buffer *buffer, int buffer_size, int expected_m_id, MeasurementInfo *req);

/* Writes one measurement to the shared sensor->controller random-access buffer.
 * Returns 1 on success, or 0 if the buffer is full.
 */
int write_sensor_controller_buffer(struct ra_buffer *buffer, int buffer_size, const MeasurementInfo *m);

/* Reads one measurement for controller_id from the shared sensor->controller buffer.
 * If there is no unread measurement from the paired sensor, sets m->m_id to -1.
 */
void read_sensor_controller_buffer(struct ra_buffer *buffer, int controller_id, int buffer_size, MeasurementInfo *m);

/* Writes one measurement to the controller->server random-access buffer.
 * Returns 1 on success, or 0 if the buffer is full.
 */
int write_controller_servers_buffer(struct ra_buffer *buffer, int buffer_size, const MeasurementInfo *m);

/* Reads the next expected measurement for one server from the controller->server random-access buffer.
 * expected_m_id and expected_controller_id identify which controller measurement this server is waiting for.
 * If that measurement is not in the buffer yet, sets m->m_id to -1.
 */
void read_controller_servers_buffer(struct ra_buffer *buffer, int buffer_size, int expected_m_id, int expected_controller_id, MeasurementInfo *m);

#endif
