#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "main.h"
#include "memory.h"
#include "process.h"

/* ===================== MAIN ===================== */
struct info_container
{
    int n_sensors;    // number of sensor processes
    int n_servers;    // number of server processes
    int buffers_size; // shared buffer size

    int *sensors_pids;     // process IDs of sensor processes
    int *controllers_pids; // process IDs of controller processes
    int *servers_pids;     // process IDs of server processes

    int *num_generated_measurements; // number of measurements generated by each sensor
    int *num_invalid_measurements;   // number of invalid measurements per sensor
    int *num_estimates;              // number of estimates produced by each server

    int *total_measurements; // total number of generated measurements in the system
    int *terminate;          // termination flag (1 means the system must stop)
};
int main(int argc, char *argv[])
{
    struct info_container info;
    struct buffers buffs;

    main_args(argc, argv, &info);

    create_dynamic_memory_structs(&info, &buffs);
    create_shared_memory_structs(&info, &buffs);

    create_processes(&info, &buffs);

    user_interaction(&info, &buffs);

    end_execution(&info, &buffs);

    destroy_shared_memory_structs(&info, &buffs);
    destroy_dynamic_memory_structs(&info, &buffs);

    return 0;
}

/* ===================== ARGUMENTOS ===================== */

void main_args(int argc, char *argv[], struct info_container *info)
{
    if (argc < 4) {
        printf("Uso: %s <n_sensors> <n_servers> <buffer_size>\n", argv[0]);
        exit(1);
    }

    info->n_sensors = atoi(argv[1]);
    info->n_servers = atoi(argv[2]);
    info->buffers_size = atoi(argv[3]);
}

/* ===================== MEMÓRIA DINÂMICA ===================== */

void create_dynamic_memory_structs(struct info_container *info, struct buffers *buffs)
{
    int n = info->n_sensors;
    int s = info->n_servers;

    info->sensors_pids = allocate_dynamic_memory(sizeof(int) * n);
    info->controllers_pids = allocate_dynamic_memory(sizeof(int) * n);
    info->servers_pids = allocate_dynamic_memory(sizeof(int) * s);

    buffs->buff_main_sensors = allocate_dynamic_memory(sizeof(struct circ_buffer));
    buffs->buff_sensors_controllers = allocate_dynamic_memory(sizeof(struct ra_buffer));
    buffs->buff_controllers_servers = allocate_dynamic_memory(sizeof(struct ra_buffer));
}

void destroy_dynamic_memory_structs(struct info_container *info, struct buffers *buffs)
{
    deallocate_dynamic_memory(info->sensors_pids);
    deallocate_dynamic_memory(info->controllers_pids);
    deallocate_dynamic_memory(info->servers_pids);

    deallocate_dynamic_memory(buffs->buff_main_sensors);
    deallocate_dynamic_memory(buffs->buff_sensors_controllers);
    deallocate_dynamic_memory(buffs->buff_controllers_servers);
}

/* ===================== MEMÓRIA PARTILHADA ===================== */

void create_shared_memory_structs(struct info_container *info, struct buffers *buffs)
{
    int n = info->n_sensors;
    int s = info->n_servers;
    int size = info->buffers_size;

    info->num_generated_measurements = create_shared_memory(ID_SHM_SENSORS_GENERATED, sizeof(int) * n);
    info->num_invalid_measurements = create_shared_memory(ID_SHM_SENSORS_INVALID, sizeof(int) * n);
    info->num_estimates = create_shared_memory(ID_SHM_SERVERS_PROCESSED, sizeof(int) * s);

    info->total_measurements = create_shared_memory(ID_SHM_TOTAL_MEASUREMENTS, sizeof(int));
    info->terminate = create_shared_memory(ID_SHM_TERMINATE, sizeof(int));

    *info->terminate = 0;

    // Buffers (versão simplificada)
    buffs->buff_main_sensors->ptrs = create_shared_memory(ID_SHM_MAIN_SENSORS_PTR, sizeof(struct pointers));
    buffs->buff_main_sensors->buffer = create_shared_memory(ID_SHM_MAIN_SENSORS_BUFFER, sizeof(MeasurementInfo) * size);

    buffs->buff_sensors_controllers->ptrs = create_shared_memory(ID_SHM_SENSORS_CONTROLLERS_PTR, sizeof(int) * size);
    buffs->buff_sensors_controllers->buffer = create_shared_memory(ID_SHM_SENSORS_CONTROLLERS_BUFFER, sizeof(MeasurementInfo) * size);

    buffs->buff_controllers_servers->ptrs = create_shared_memory(ID_SHM_CONTROLLERS_SERVERS_VERSION, sizeof(int) * size);
    buffs->buff_controllers_servers->buffer = create_shared_memory(ID_SHM_CONTROLLERS_SERVERS_LATEST, sizeof(MeasurementInfo) * size);
}

void destroy_shared_memory_structs(struct info_container *info, struct buffers *buffs)
{
    int n = info->n_sensors;
    int s = info->n_servers;
    int size = info->buffers_size;

    destroy_shared_memory(ID_SHM_SENSORS_GENERATED, info->num_generated_measurements, sizeof(int) * n);
    destroy_shared_memory(ID_SHM_SENSORS_INVALID, info->num_invalid_measurements, sizeof(int) * n);
    destroy_shared_memory(ID_SHM_SERVERS_PROCESSED, info->num_estimates, sizeof(int) * s);

    destroy_shared_memory(ID_SHM_TOTAL_MEASUREMENTS, info->total_measurements, sizeof(int));
    destroy_shared_memory(ID_SHM_TERMINATE, info->terminate, sizeof(int));

    destroy_shared_memory(ID_SHM_MAIN_SENSORS_PTR, buffs->buff_main_sensors->ptrs, sizeof(struct pointers));
    destroy_shared_memory(ID_SHM_MAIN_SENSORS_BUFFER, buffs->buff_main_sensors->buffer, sizeof(MeasurementInfo) * size);

    destroy_shared_memory(ID_SHM_SENSORS_CONTROLLERS_PTR, buffs->buff_sensors_controllers->ptrs, sizeof(int) * size);
    destroy_shared_memory(ID_SHM_SENSORS_CONTROLLERS_BUFFER, buffs->buff_sensors_controllers->buffer, sizeof(MeasurementInfo) * size);

    destroy_shared_memory(ID_SHM_CONTROLLERS_SERVERS_VERSION, buffs->buff_controllers_servers->ptrs, sizeof(int) * size);
    destroy_shared_memory(ID_SHM_CONTROLLERS_SERVERS_LATEST, buffs->buff_controllers_servers->buffer, sizeof(MeasurementInfo) * size);
}

/* ===================== PROCESSOS ===================== */

void create_processes(struct info_container *info, struct buffers *buffs)
{
    for (int i = 0; i < info->n_sensors; i++)
        info->sensors_pids[i] = launch_process(SENSOR_PROCESS, i, info, buffs);

    for (int i = 0; i < info->n_sensors; i++)
        info->controllers_pids[i] = launch_process(CONTROLLER_PROCESS, i, info, buffs);

    for (int i = 0; i < info->n_servers; i++)
        info->servers_pids[i] = launch_process(SERVER_PROCESS, i, info, buffs);
}

void wait_processes(struct info_container *info)
{
    for (int i = 0; i < info->n_sensors; i++)
        wait_process(info->sensors_pids[i]);

    for (int i = 0; i < info->n_sensors; i++)
        wait_process(info->controllers_pids[i]);

    for (int i = 0; i < info->n_servers; i++)
        wait_process(info->servers_pids[i]);
}

/* ===================== INTERAÇÃO ===================== */

void user_interaction(struct info_container *info, struct buffers *buffs)
{
    char command[50];

    while (!(*info->terminate)) {
        printf("> ");
        scanf("%s", command);

        if (strcmp(command, "help") == 0)
            help();
        else if (strcmp(command, "stats") == 0)
            print_stat(info);
        else if (strcmp(command, "exit") == 0)
            break;
        else
            printf("Comando desconhecido\n");
    }
}

/* ===================== TERMINAR ===================== */

void end_execution(struct info_container *info, struct buffers *buffs)
{
    *info->terminate = 1;

    wait_processes(info);

    write_final_statistics(info);
}

/* ===================== OUTPUT ===================== */

void write_final_statistics(struct info_container *info)
{
    printf("\n=== Estatísticas Finais ===\n");

    for (int i = 0; i < info->n_sensors; i++) {
        printf("Sensor %d -> geradas: %d inválidas: %d\n",
               i,
               info->num_generated_measurements[i],
               info->num_invalid_measurements[i]);
    }

    for (int i = 0; i < info->n_servers; i++) {
        printf("Server %d -> estimativas: %d\n",
               i,
               info->num_estimates[i]);
    }

    printf("Total medições: %d\n", *info->total_measurements);
}

void print_stat(struct info_container *info)
{
    printf("\n=== Estado do Sistema ===\n");
    printf("Sensores: %d\n", info->n_sensors);
    printf("Servers: %d\n", info->n_servers);
    printf("Buffer size: %d\n", info->buffers_size);
}

void help(void)
{
    printf("\nComandos:\n");
    printf("help - ajuda\n");
    printf("stats - estado do sistema\n");
    printf("exit - terminar\n");
}

/* ===================== EXTRA ===================== */

void read_estimate(struct info_container *info, int m_id)
{
    printf("Pedido de estimate para m_id=%d (não implementado ainda)\n", m_id);
}